kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: java-adoptopenjdk
    app: java
  name: java-adoptopenjdk
  namespace: java
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: java-adoptopenjdk
  template:
    metadata:
      labels:
        k8s-app: java-adoptopenjdk
        app: java
    spec:
      containers:
        - name: java-adoptopenjkd
          resources:
            limits:
              memory: %MEM_LIMIT%
          image: adoptopenjdk:12.0.2_10-jre-openj9-0.15.1
          imagePullPolicy: Always
          command: ["/bin/bash", "-c", "curl -L https://github.com/jelastic/java-vertical-scaling-test/raw/master/dist/app.jar --output app.jar && sleep 10 && echo -ne '\n' | java %JAVA_OPTS% -jar app.jar 30"]
      nodeSelector:
        java: adoptjdk
