kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: java-zing
    app: java
  name: java-zing
  namespace: java
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: java-zing
  template:
    metadata:
      labels:
        k8s-app: java-zing
        app: java
    spec:
      containers:
        - name: java-zing
          image: devbeta/javaengine:zing-11.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: %MEM_LIMIT%
          command: ["/bin/bash", "-c", "curl -L https://github.com/jelastic/java-vertical-scaling-test/raw/master/dist/app.jar --output app.jar && sleep 10 && echo -ne '\n' | java %JAVA_OPTS% -jar app.jar 30"]
      nodeSelector:
        java: zing
